### ISSUE TITLE
Support recursive download

### ISSUE THREAD

**Issue by NickMcAvoy** [mgk/s3-plugin#2]
The aws cli supports a `--recursive` flag on the `cp` task for getting all objects under a specified prefix and putting them into a directory. What would it take to support that functionality with this `gradle` plugin?

**Comment by mgk** [comment]
That makes sense. It used to be one had to list the S3 bucket and then issue batches of download requests which was a pain. Now it looks like [TransferManager.downloadDirectory](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManager.html#downloadDirectory-java.lang.String-java.lang.String-java.io.File-) makes that much easier and more efficient.

I'd add `keyPrefix` and `destDir` properties to `S3Download` to indicate a recursive download is desired. Ideally there should also be a `timeout` property to abort download transfers that take too long. Finally we should add a progress listener to report progress.

I don't need this functionality myself currently, but it makes sense to have so I may give it a go. In the meantime I'd welcome a pull request that used the transfer manager as above.

**Comment by NickMcAvoy** [comment]
Progress is underway in [my little fork](https://github.com/NickMcAvoy/s3-plugin). I have basic downloading implemented, but still print statements in place of real use of the `ProgressListener`, no timeout, and I didn't figure out how to alternately require `key/file` or `keyPrefix/destDir` rather than all four.

**Comment by NickMcAvoy** [comment]
Also, I'm new to groovy and doing this a bit hastily, so the code quality could probably be cleaned up.

**Comment by mgk** [comment]
@NickMcAvoy Thanks for getting the ball rolling on this. I implemented recursive downloads as described above except for the timeout property which is directly supported on single file downloads but looks like it requires some additional state management for multi-file downloads.

I've tested it with a handful of files. Let me know how it works for you.
