### ISSUE TITLE
The maven repo address seems to be wrong

### ISSUE THREAD

**Issue by palto-blubek** [mgk/s3-plugin#8]
Trying to use this plugin, I get:

```
> Could not find gradle.plugin.com.github.mgk.gradle:s3:1.5.0.
                 Searched in the following locations:
                     https://plugins.gradle.org/m2/gradle/plugin/com/github/mgk/gradle/s3/1.5.0/s3-1.5.0.pom
                     https://plugins.gradle.org/m2/gradle/plugin/com/github/mgk/gradle/s3/1.5.0/s3-1.5.0.jar

```

**Comment by mgk** [comment]
tl;dr: change `1.5.0` to `1.4.0`

Yeah the latest release is 1.4.0. The develop branch is for the next release will be 1.5.0. I had set the default Github branch to be develop so I could merge PRs to develop more conveniently, but it looks like that has the side effect of making the develop version of the README the one people see by default.

I updated the default Github branch to be `master` to avoid this in the future.
