### ISSUE TITLE
Plugin does not appear to see all my project.s3 properties

### ISSUE THREAD

**Issue by boatmisser** [mgk/s3-plugin#9]
I may very well have done something daft however, with my build.gradle (gradle 3.5), neither the region nor profile properties appear to be used by the plugin, bucket however is.
```
s3 {
  region = 'ap-southeast-2'
  profile = 'my-profile'
  bucket = 'myaccount-resources'
}
```
The profile property appears to be ignored, to get further I has to set the AWS environment variables.
Once that was done I then got the following error:
```
Unable to execute HTTP request: Connect to myaccount-resources.s3-us-west-1.amazonaws.com:443
```
So while it has picked up the bucket it has not used the region I defined.
So it seems that only bucket is readable by the plugin, profile and region appear to be ignored.

**Comment by mgk** [comment]
By any chance are you setting env vars for the profile and region? It may be that they env vars are overriding the gradle settings.

http://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html
